encapp: script: fix unittest
Tested:

Before:
```
 $ ./scripts/tests/unit/app_utils_test.py
F..
======================================================================
FAIL: test_install_app_shall_install_encapp_apk (__main__.TestAppUtils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "encapp/./scripts/tests/unit/app_utils_test.py", line 29, in test_install_app_shall_install_encapp_apk
    mock_perm_store.assert_called_with(ADB_DEVICE_VALID_ID, 0)
  File "/usr/lib64/python3.10/unittest/mock.py", line 919, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
Expected: grant_storage_permissions('1234567890abcde', 0)
Actual: grant_storage_permissions('1234567890abcde', 'com.facebook.encapp', 0)

----------------------------------------------------------------------
Ran 3 tests in 0.004s

FAILED (failures=1)
```

After:
```
$ ./scripts/tests/unit/app_utils_test.py
...
----------------------------------------------------------------------
Ran 3 tests in 0.003s

OK
```