encapp: rework error reporting
app (java) to script (python) results reporting is based on the former
writing a specific line at the logcat, and the latter reading it. This
patch enforces a specific syntax in such message, including the
test id, run id, result, and error code (if existing)

Includes:
* move java error reporting to `report_result()` function.
* adding parsing code in the python script.
* adding a `return_ok` parameter to most functions, so that
  `main()` can return -1 if there were problems.

Tested:

Before:
(0) ok (ask for a valid encoder)
```
$ ./scripts/encapp.py run ~/proj/encapp/tests/bitrate_buffer.pbtxt --device-workdir /data/data/com.facebook.encapp -i /tmp/out.y4m --codec omx.google.h264.encoder --bitrate 1Mbps --local-workdir /tmp/testing1/
com.facebook.encapp was not active
results collect: ['/tmp/testing1/encapp_7013ce03-8f77-4498-8773-bd4539123357.json']
$ echo $?
0
```

(1) error (ask for an invalid encoder)
```
$ ./scripts/encapp.py run ~/proj/encapp/tests/bitrate_buffer.pbtxt --device-workdir /data/data/com.facebook.encapp -i /tmp/out.y4m --codec invalid.encoder.here --bitrate 1Mbps --local-workdir /tmp/testing1/
com.facebook.encapp was not active
results collect: ['/tmp/testing1/encapp_cffd939c-7367-4155-b23d-ba8329567c67.json']
**********

Test case failed:
"Verify encoding bitrate - buffer"

**********
logcat has been saved to "/tmp/testing1//logcat.txt"
$ echo $?
0
```

After:
(0) ok (ask for a valid encoder)
```
$ ./scripts/encapp.py run ~/proj/encapp/tests/bitrate_buffer.pbtxt --device-workdir /data/data/com.facebook.encapp -i /tmp/out.y4m --codec omx.google.h264.encoder --bitrate 1Mbps --local-workdir /tmp/testing1/
com.facebook.encapp was not active
results collect: ['/tmp/testing1/encapp_68cb8613-bad1-4ffc-9525-7d7c31218d49.json']
ok: test id: "bitrate_buffer.1000000" run_id: encapp_68cb8613-bad1-4ffc-9525-7d7c31218d49 result: ok
$ echo $?
0
```

(1) error (ask for an invalid encoder)
```
$ ./scripts/encapp.py run ~/proj/encapp/tests/bitrate_buffer.pbtxt --device-workdir /data/data/com.facebook.encapp -i /tmp/out.y4m --codec invalid.encoder.here --bitrate 1Mbps --local-workdir /tmp/testing1/
com.facebook.encapp was not active
results collect: ['/tmp/testing1/encapp_e5e68328-b385-4caf-8e3f-b765d8acfbe9.json']
error: test id: "bitrate_buffer.1000000" run_id: encapp_e5e68328-b385-4caf-8e3f-b765d8acfbe9 result: error error_code: "No matching codecs for "invalid.encoder.here""
logcat has been saved to "/tmp/testing1//logcat.txt"
$ echo $?
255
```